#!/bin/bash

. /etc/transmission/default

docker stop transmission || true
docker rm transmission || true

docker run -d \
  --name=transmission \
  -e USER=user \
  -e PASS=dummy \
  -e PUID=109 \
  -e PGID=116 \
  -p 9091:9091 \
  -p 13777:13777 \
  -p 13777:13777/udp \
  -v /var/lib/transmission/config:/config \
  -v /storage/tmp/torrent/complete:/downloads \
  --restart unless-stopped \
  custom_linuxserver_transmission:latest
#  lscr.io/linuxserver/transmission:latest

